### ISSUE TITLE
Test page: Detailed review checklist

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-discuss#24]
# Detailed internationalisation review checklist
Check marks indicate requirements that are fulfilled by this spec. Add comments to describe conformance.

This checklist was created <a href="https://www.w3.org/TR/international-specs/#language_checklist">here</a>.

### Language basics
1. [x] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> It should be possible to associate a language with any piece of <a data-cite="i18n-glossary" data-cite-path="/" data-cite-frag="def_localizable_text" data-type="dfn" href="https://www.w3.org/TR/i18n-glossary/#def_localizable_text">localizable text</a> or <a data-cite="i18n-glossary" data-cite-path="/" data-cite-frag="def_natural_language" data-type="dfn" href="https://www.w3.org/TR/i18n-glossary/#def_natural_language">natural language</a> content. <a href="https://www.w3.org/TR/international-specs/#lang_basics_1" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [x] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Where possible, there should  be a way to label <a data-cite="i18n-glossary" data-cite-path="/" data-cite-frag="def_natural_language" data-type="dfn" href="https://www.w3.org/TR/i18n-glossary/#def_natural_language">natural language</a> changes in inline text. <a href="https://www.w3.org/TR/international-specs/#lang_basics_inline" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Consider whether it is useful to express the <a href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_meta">intended linguistic audience</a> of a resource, in addition to specifying the language used for <a href="https://w3c.github.io/bp-i18n-specdev/#sec_text_processing_lang">text processing</a>. <a href="https://www.w3.org/TR/international-specs/#lang_basics_meta" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [x] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> A language declaration that indicates the <a data-link-type="dfn" data-cite="i18n-glossary" data-cite-path="/" data-cite-frag="def_text_processing_language" data-type="dfn" href="https://www.w3.org/TR/i18n-glossary/#def_text_processing_language">text-processing language</a> for a range of text must associate  a single language  value with a specific range of text. <a href="https://www.w3.org/TR/international-specs/#tp_lang_values" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

### Defining language values
1. [x] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Values for language declarations must use BCP 47. <a href="https://www.w3.org/TR/international-specs/#lang_use_bcp47" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [x] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Refer to BCP 47, not to RFC 5646. <a href="https://www.w3.org/TR/international-specs/#lang_bcp_not_rfc" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Be specific about what level of conformance you expect for language tags: BCP 47 defines two levels of conformance, "valid" and "well-formed". <a href="https://www.w3.org/TR/international-specs/#lang_values_specificity" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

**Comment by r12a** [comment]
# Detailed internationalisation review checklist
Check marks indicate requirements that are fulfilled by this spec. Add comments to describe conformance.

This checklist was created <a href="https://www.w3.org/TR/international-specs/#text_direction_checklist">here</a>.

## 3. Text direction
### Basic requirements
1. [x] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> It must be possible to indicate base direction for each individual paragraph-level item of <a data-cite="i18n-glossary" data-cite-path="/" data-cite-frag="def_natural_language" data-type="dfn" href="https://www.w3.org/TR/i18n-glossary/#def_natural_language">natural language</a> text that will be read by someone. <a href="https://www.w3.org/TR/international-specs/#dir_paragraphs" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [x] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> It must be possible to indicate base direction changes for embedded runs of inline bidirectional text for all <a data-cite="i18n-glossary" data-cite-path="/" data-cite-frag="def_localizable_text" data-type="dfn" href="https://www.w3.org/TR/i18n-glossary/#def_localizable_text">localizable text</a>. <a href="https://www.w3.org/TR/international-specs/#dir_inline" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Annotating right-to-left text must require the minimum amount of effort for people who work natively with right-to-left scripts. <a href="https://www.w3.org/TR/international-specs/#dir_reasonable" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

### Background information
1. [x] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Do not assume that direction can be determined from language information. <a href="https://www.w3.org/TR/international-specs/#bidi_lang" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

### Base direction values
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> Values for the default base direction should include left-to-right, right-to-left, and auto. <a href="https://www.w3.org/TR/international-specs/#bidi_values" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

### Handling direction in markup
1. [x] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> The spec should  indicate how to define a default base direction for the resource as a whole, ie. set the overall base direction. <a href="https://www.w3.org/TR/international-specs/#bidi_whole_res" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [x] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> The  default base direction, in the absence of other information, should be LTR. <a href="https://www.w3.org/TR/international-specs/#bidi_res_default" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [ ] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> The content author must be able to indicate parts of the text where the base direction changes. At the block level, this should be achieved using attributes or metadata, and should not rely on Unicode control characters. <a href="https://www.w3.org/TR/international-specs/#bidi_block_change" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_
1. [x] <input type="checkbox" class="relevance" title="Check if this requirement is relevant to your spec."><input type="checkbox" class="ok" title="Check if your spec meets this requirement." onclick="this.previousSibling.checked=true"> It must be possible to also set the direction for content fragments to <code class="kw" translate="no">auto</code>. This means that the base direction will be determined by examining the content itself. <a href="https://www.w3.org/TR/international-specs/#bidi_block_auto" class="checklistMore" target="_blank">more</a><br>    _Comments_go_here_

### Handling base direction for strings

### Setting base direction for inline or substring text
